#############################################################################
# Makefile for building: MIPS_SystemC
# Generated by qmake (2.01a) (Qt 4.8.6) on: qua Nov 4 02:59:27 2015
# Project:  MIPS_SystemC.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile MIPS_SystemC.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -fpermissive -O2 -fpermissive -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -fpermissive -O2 -fpermissive -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I$(SYSTEMC)/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L$(SYSTEMC)/lib-linux64 -L$(SYSTEMC)/lib-linux -lsystemc -lpthread -lQt3Support -lQtGui -lQtCore 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mips.cpp \
		imem.cpp \
		decode.cpp \
		regfile.cpp \
		alu.cpp \
		dmem.cpp \
		control.cpp \
		mem32.cpp \
		reg.cpp \
		add.cpp \
		gates.cpp \
		ext.cpp \
		shiftl2.cpp \
		hazard.cpp \
		jbrcalc.cpp \
		control_jbr.cpp \
		comp.cpp \
		mipsaux.cpp \
		GUI/MIPSctrl.cpp \
		GUI/MIPSarch.cpp \
		GUI/MIPSmods.cpp \
		GUI/modview.cpp \
		GUI/MIPSimemview.cpp \
		GUI/MIPSdmemview.cpp \
		GUI/MIPSregfileview.cpp \
		GUI/MIPSmemview.cpp \
		GUI/PortValItem.cpp \
		GUI/PortValRead.cpp moc_MIPSctrl.cpp \
		moc_MIPSarch.cpp \
		moc_MIPSmods.cpp \
		moc_modview.cpp \
		moc_MIPSimemview.cpp \
		moc_MIPSregfileview.cpp \
		moc_MIPSdmemview.cpp \
		moc_MIPSmemview.cpp
OBJECTS       = main.o \
		mips.o \
		imem.o \
		decode.o \
		regfile.o \
		alu.o \
		dmem.o \
		control.o \
		mem32.o \
		reg.o \
		add.o \
		gates.o \
		ext.o \
		shiftl2.o \
		hazard.o \
		jbrcalc.o \
		control_jbr.o \
		comp.o \
		mipsaux.o \
		MIPSctrl.o \
		MIPSarch.o \
		MIPSmods.o \
		modview.o \
		MIPSimemview.o \
		MIPSdmemview.o \
		MIPSregfileview.o \
		MIPSmemview.o \
		PortValItem.o \
		PortValRead.o \
		moc_MIPSctrl.o \
		moc_MIPSarch.o \
		moc_MIPSmods.o \
		moc_modview.o \
		moc_MIPSimemview.o \
		moc_MIPSregfileview.o \
		moc_MIPSdmemview.o \
		moc_MIPSmemview.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		MIPS_SystemC.pro
QMAKE_TARGET  = MIPS_SystemC
DESTDIR       = 
TARGET        = MIPS_SystemC

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MIPS_SystemC.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQt3Support.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile MIPS_SystemC.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQt3Support.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile MIPS_SystemC.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MIPS_SystemC1.0.0 || $(MKDIR) .tmp/MIPS_SystemC1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MIPS_SystemC1.0.0/ && $(COPY_FILE) --parents mips.h imem.h decode.h regfile.h alu.h dmem.h control.h mem32.h mux.h reg.h add.h gates.h ext.h shiftl2.h regT.h reg_id_exe.h reg_exe_mem.h reg_mem_wb.h hazard.h mipsaux.h jbrcalc.h control_jbr.h GUI/MIPSctrl.h GUI/MIPSarch.h GUI/MIPSmods.h GUI/modview.h GUI/MIPSimemview.h GUI/MIPSregfileview.h GUI/MIPSdmemview.h GUI/MIPSmemview.h GUI/PortValItem.h GUI/PortValRead.h GUI/cycle.xpm GUI/reset.xpm GUI/regs.xpm GUI/datamem.xpm GUI/instmem.xpm GUI/readimem.xpm GUI/readdmem.xpm .tmp/MIPS_SystemC1.0.0/ && $(COPY_FILE) --parents main.cpp mips.cpp imem.cpp decode.cpp regfile.cpp alu.cpp dmem.cpp control.cpp mem32.cpp reg.cpp add.cpp gates.cpp ext.cpp shiftl2.cpp hazard.cpp jbrcalc.cpp control_jbr.cpp comp.cpp mipsaux.cpp GUI/MIPSctrl.cpp GUI/MIPSarch.cpp GUI/MIPSmods.cpp GUI/modview.cpp GUI/MIPSimemview.cpp GUI/MIPSdmemview.cpp GUI/MIPSregfileview.cpp GUI/MIPSmemview.cpp GUI/PortValItem.cpp GUI/PortValRead.cpp .tmp/MIPS_SystemC1.0.0/ && (cd `dirname .tmp/MIPS_SystemC1.0.0` && $(TAR) MIPS_SystemC1.0.0.tar MIPS_SystemC1.0.0 && $(COMPRESS) MIPS_SystemC1.0.0.tar) && $(MOVE) `dirname .tmp/MIPS_SystemC1.0.0`/MIPS_SystemC1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MIPS_SystemC1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MIPSctrl.cpp moc_MIPSarch.cpp moc_MIPSmods.cpp moc_modview.cpp moc_MIPSimemview.cpp moc_MIPSregfileview.cpp moc_MIPSdmemview.cpp moc_MIPSmemview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MIPSctrl.cpp moc_MIPSarch.cpp moc_MIPSmods.cpp moc_modview.cpp moc_MIPSimemview.cpp moc_MIPSregfileview.cpp moc_MIPSdmemview.cpp moc_MIPSmemview.cpp
moc_MIPSctrl.cpp: GUI/MIPSctrl.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) GUI/MIPSctrl.h -o moc_MIPSctrl.cpp

moc_MIPSarch.cpp: GUI/MIPSarch.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) GUI/MIPSarch.h -o moc_MIPSarch.cpp

moc_MIPSmods.cpp: GUI/MIPSmods.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) GUI/MIPSmods.h -o moc_MIPSmods.cpp

moc_modview.cpp: GUI/modview.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) GUI/modview.h -o moc_modview.cpp

moc_MIPSimemview.cpp: GUI/MIPSmemview.h \
		GUI/MIPSimemview.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) GUI/MIPSimemview.h -o moc_MIPSimemview.cpp

moc_MIPSregfileview.cpp: GUI/MIPSmemview.h \
		GUI/MIPSregfileview.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) GUI/MIPSregfileview.h -o moc_MIPSregfileview.cpp

moc_MIPSdmemview.cpp: GUI/MIPSmemview.h \
		GUI/MIPSdmemview.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) GUI/MIPSdmemview.h -o moc_MIPSdmemview.cpp

moc_MIPSmemview.cpp: GUI/MIPSmemview.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) GUI/MIPSmemview.h -o moc_MIPSmemview.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp GUI/MIPSctrl.h \
		mips.h \
		imem.h \
		mem32.h \
		decode.h \
		regfile.h \
		alu.h \
		dmem.h \
		control.h \
		hazard.h \
		mux.h \
		reg.h \
		ext.h \
		shiftl2.h \
		add.h \
		gates.h \
		regT.h \
		reg_if_id.h \
		reg_id_exe.h \
		reg_exe_mem.h \
		reg_mem_wb.h \
		reg_id1_id2.h \
		mux4.h \
		comp.h \
		control_jbr.h \
		jbrcalc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mips.o: mips.cpp mips.h \
		imem.h \
		mem32.h \
		decode.h \
		regfile.h \
		alu.h \
		dmem.h \
		control.h \
		hazard.h \
		mux.h \
		reg.h \
		ext.h \
		shiftl2.h \
		add.h \
		gates.h \
		regT.h \
		reg_if_id.h \
		reg_id_exe.h \
		reg_exe_mem.h \
		reg_mem_wb.h \
		reg_id1_id2.h \
		mux4.h \
		comp.h \
		control_jbr.h \
		jbrcalc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mips.o mips.cpp

imem.o: imem.cpp imem.h \
		mem32.h \
		mipsaux.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imem.o imem.cpp

decode.o: decode.cpp decode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o decode.o decode.cpp

regfile.o: regfile.cpp regfile.h \
		mem32.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o regfile.o regfile.cpp

alu.o: alu.cpp alu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alu.o alu.cpp

dmem.o: dmem.cpp dmem.h \
		mem32.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dmem.o dmem.cpp

control.o: control.cpp control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o control.o control.cpp

mem32.o: mem32.cpp mem32.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mem32.o mem32.cpp

reg.o: reg.cpp reg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reg.o reg.cpp

add.o: add.cpp add.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o add.o add.cpp

gates.o: gates.cpp gates.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gates.o gates.cpp

ext.o: ext.cpp ext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ext.o ext.cpp

shiftl2.o: shiftl2.cpp shiftl2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shiftl2.o shiftl2.cpp

hazard.o: hazard.cpp hazard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hazard.o hazard.cpp

jbrcalc.o: jbrcalc.cpp jbrcalc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jbrcalc.o jbrcalc.cpp

control_jbr.o: control_jbr.cpp control_jbr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o control_jbr.o control_jbr.cpp

comp.o: comp.cpp comp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o comp.o comp.cpp

mipsaux.o: mipsaux.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mipsaux.o mipsaux.cpp

MIPSctrl.o: GUI/MIPSctrl.cpp mips.h \
		imem.h \
		mem32.h \
		decode.h \
		regfile.h \
		alu.h \
		dmem.h \
		control.h \
		hazard.h \
		mux.h \
		reg.h \
		ext.h \
		shiftl2.h \
		add.h \
		gates.h \
		regT.h \
		reg_if_id.h \
		reg_id_exe.h \
		reg_exe_mem.h \
		reg_mem_wb.h \
		reg_id1_id2.h \
		mux4.h \
		comp.h \
		control_jbr.h \
		jbrcalc.h \
		GUI/MIPSmods.h \
		GUI/MIPSarch.h \
		GUI/MIPSimemview.h \
		GUI/MIPSmemview.h \
		GUI/MIPSdmemview.h \
		GUI/MIPSregfileview.h \
		GUI/MIPSctrl.h \
		GUI/readimem.xpm \
		GUI/readdmem.xpm \
		GUI/cycle.xpm \
		GUI/reset.xpm \
		GUI/instmem.xpm \
		GUI/datamem.xpm \
		GUI/regs.xpm
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MIPSctrl.o GUI/MIPSctrl.cpp

MIPSarch.o: GUI/MIPSarch.cpp GUI/PortValItem.h \
		GUI/PortValRead.h \
		GUI/MIPSarch.h \
		mips.h \
		imem.h \
		mem32.h \
		decode.h \
		regfile.h \
		alu.h \
		dmem.h \
		control.h \
		hazard.h \
		mux.h \
		reg.h \
		ext.h \
		shiftl2.h \
		add.h \
		gates.h \
		regT.h \
		reg_if_id.h \
		reg_id_exe.h \
		reg_exe_mem.h \
		reg_mem_wb.h \
		reg_id1_id2.h \
		mux4.h \
		comp.h \
		control_jbr.h \
		jbrcalc.h \
		mipsaux.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MIPSarch.o GUI/MIPSarch.cpp

MIPSmods.o: GUI/MIPSmods.cpp mips.h \
		imem.h \
		mem32.h \
		decode.h \
		regfile.h \
		alu.h \
		dmem.h \
		control.h \
		hazard.h \
		mux.h \
		reg.h \
		ext.h \
		shiftl2.h \
		add.h \
		gates.h \
		regT.h \
		reg_if_id.h \
		reg_id_exe.h \
		reg_exe_mem.h \
		reg_mem_wb.h \
		reg_id1_id2.h \
		mux4.h \
		comp.h \
		control_jbr.h \
		jbrcalc.h \
		GUI/modview.h \
		GUI/MIPSmods.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MIPSmods.o GUI/MIPSmods.cpp

modview.o: GUI/modview.cpp GUI/PortValItem.h \
		GUI/modview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modview.o GUI/modview.cpp

MIPSimemview.o: GUI/MIPSimemview.cpp imem.h \
		mem32.h \
		mipsaux.h \
		GUI/PortValRead.h \
		GUI/MIPSimemview.h \
		GUI/MIPSmemview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MIPSimemview.o GUI/MIPSimemview.cpp

MIPSdmemview.o: GUI/MIPSdmemview.cpp dmem.h \
		mem32.h \
		GUI/MIPSdmemview.h \
		GUI/MIPSmemview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MIPSdmemview.o GUI/MIPSdmemview.cpp

MIPSregfileview.o: GUI/MIPSregfileview.cpp regfile.h \
		mem32.h \
		GUI/MIPSregfileview.h \
		GUI/MIPSmemview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MIPSregfileview.o GUI/MIPSregfileview.cpp

MIPSmemview.o: GUI/MIPSmemview.cpp mem32.h \
		GUI/MIPSmemview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MIPSmemview.o GUI/MIPSmemview.cpp

PortValItem.o: GUI/PortValItem.cpp GUI/PortValRead.h \
		GUI/PortValItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PortValItem.o GUI/PortValItem.cpp

PortValRead.o: GUI/PortValRead.cpp GUI/PortValRead.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PortValRead.o GUI/PortValRead.cpp

moc_MIPSctrl.o: moc_MIPSctrl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MIPSctrl.o moc_MIPSctrl.cpp

moc_MIPSarch.o: moc_MIPSarch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MIPSarch.o moc_MIPSarch.cpp

moc_MIPSmods.o: moc_MIPSmods.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MIPSmods.o moc_MIPSmods.cpp

moc_modview.o: moc_modview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modview.o moc_modview.cpp

moc_MIPSimemview.o: moc_MIPSimemview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MIPSimemview.o moc_MIPSimemview.cpp

moc_MIPSregfileview.o: moc_MIPSregfileview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MIPSregfileview.o moc_MIPSregfileview.cpp

moc_MIPSdmemview.o: moc_MIPSdmemview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MIPSdmemview.o moc_MIPSdmemview.cpp

moc_MIPSmemview.o: moc_MIPSmemview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MIPSmemview.o moc_MIPSmemview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

